# Generated by Django 5.1.2 on 2024-10-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_customfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='custom_fields',
            field=models.JSONField(default=dict),
        ),
    ]
